import type { PaymentMethod } from "@prisma/client";

export const SELECTED_FUTURE_PAYMENT_PROVIDER = "flutterwave" as const;

export type ProviderPaymentStatus =
  | "pending"
  | "processing"
  | "confirmed"
  | "failed"
  | "refunded";

// Flutterwave is Sonder's selected future online provider, but billing stays
// provider-independent. A future adapter should map these generic fields to
// Flutterwave values without leaking Flutterwave types into invoices,
// subscriptions, or payment records:
// - sonderTransactionReference -> Flutterwave tx_ref / reference generated by Sonder
// - providerTransactionId -> Flutterwave transaction_id or charge data.id
// - providerReference -> Flutterwave flw_ref / processor reference
// - providerTransactionToken -> optional hosted-checkout/session token if provided
export type PaymentCheckoutInput = {
  invoiceId: string;
  sonderTransactionReference: string;
  amountMinor: bigint;
  currency: string;
  returnUrl: string;
};

export type PaymentVerificationInput = {
  invoiceId: string;
  sonderTransactionReference: string;
  providerTransactionId: string;
  providerReference?: string | null;
  amountMinor: bigint;
  currency: string;
};

export type PaymentStatusCheckInput = PaymentVerificationInput;

export type PaymentWebhookInput = {
  rawBody: string;
  parsedBody?: unknown;
  headers: Record<string, string | string[] | undefined>;
};

export type PaymentWebhookResult = {
  eventId?: string | null;
  invoiceId?: string | null;
  sonderTransactionReference?: string | null;
  providerTransactionId: string;
  providerTransactionToken?: string | null;
  providerReference?: string | null;
  providerStatus?: string | null;
  status: ProviderPaymentStatus;
  amountMinor?: bigint;
  currency?: string;
};

export type PaymentRefundInput = {
  invoiceId: string;
  sonderTransactionReference: string;
  providerTransactionId: string;
  providerReference?: string | null;
  amountMinor: bigint;
  currency: string;
  reason?: string;
};

export type PaymentProviderResult<T> =
  | {
      status: "disabled";
      message: string;
    }
  | {
      status: "ok";
      data: T;
    }
  | {
      status: "failed";
      error: string;
      retryable: boolean;
    };

export type PaymentProviderCheckout = {
  checkoutUrl: string;
  invoiceId: string;
  sonderTransactionReference: string;
  providerTransactionId: string;
  providerTransactionToken?: string | null;
  providerReference?: string | null;
};

export type PaymentProviderVerification = {
  invoiceId?: string | null;
  sonderTransactionReference?: string | null;
  providerTransactionId: string;
  providerTransactionToken?: string | null;
  providerReference?: string | null;
  providerStatus?: string | null;
  status?: ProviderPaymentStatus;
  amountMinor?: bigint;
  currency?: string;
  confirmed: boolean;
  method?: PaymentMethod;
};

export type PaymentProviderRefund = {
  invoiceId?: string | null;
  sonderTransactionReference?: string | null;
  providerTransactionId: string;
  providerTransactionToken?: string | null;
  providerReference?: string | null;
  refundTransactionId?: string | null;
  providerStatus?: string | null;
};

export type PaymentProvider = {
  name: string;
  isConfigured: boolean;
  createCheckout(
    input: PaymentCheckoutInput,
  ): Promise<PaymentProviderResult<PaymentProviderCheckout>>;
  verifyPayment(
    input: PaymentVerificationInput,
  ): Promise<PaymentProviderResult<PaymentProviderVerification>>;
  checkPaymentStatus(
    input: PaymentStatusCheckInput,
  ): Promise<PaymentProviderResult<PaymentProviderVerification>>;
  parseWebhook(
    input: PaymentWebhookInput,
  ): Promise<PaymentProviderResult<PaymentWebhookResult>>;
  refundPayment(
    input: PaymentRefundInput,
  ): Promise<PaymentProviderResult<PaymentProviderRefund>>;
};

const disabledResult = {
  status: "disabled" as const,
  message:
    "Online payments are not enabled. Record verified offline payments manually.",
};

const disabledProvider: PaymentProvider = {
  name: "disabled",
  isConfigured: false,
  async createCheckout() {
    return disabledResult;
  },
  async verifyPayment() {
    return disabledResult;
  },
  async checkPaymentStatus() {
    return disabledResult;
  },
  async parseWebhook() {
    return disabledResult;
  },
  async refundPayment() {
    return disabledResult;
  },
};

function unsupportedProvider(name: string): PaymentProvider {
  return {
    name,
    isConfigured: false,
    async createCheckout() {
      return {
        status: "disabled",
        message: `Payment provider "${name}" is not implemented in this build.`,
      };
    },
    async verifyPayment() {
      return {
        status: "disabled",
        message: `Payment provider "${name}" is not implemented in this build.`,
      };
    },
    async checkPaymentStatus() {
      return {
        status: "disabled",
        message: `Payment provider "${name}" is not implemented in this build.`,
      };
    },
    async parseWebhook() {
      return {
        status: "disabled",
        message: `Payment provider "${name}" is not implemented in this build.`,
      };
    },
    async refundPayment() {
      return {
        status: "disabled",
        message: `Payment provider "${name}" is not implemented in this build.`,
      };
    },
  };
}

export function getPaymentProvider(): PaymentProvider {
  const configuredProvider = process.env.SONDER_PAYMENT_PROVIDER?.trim();

  if (configuredProvider && configuredProvider !== "disabled") {
    return unsupportedProvider(configuredProvider);
  }

  return disabledProvider;
}
